package com.gilgamesh.memory;

import com.gilgamesh.model.Intent;
import java.time.Instant;

/**
 * ConversationTurn — Represents a single message exchange (turn) in the conversation.
 *
 * This includes the raw message from the user, the response generated by the bot,
 * the intent matched by the classifier, and the exact timestamp of the turn.
 * It is a simple, immutable data object designed to populate the conversation history.
 */
public class ConversationTurn {

    private final String userMessage;
    private final String botResponse;
    private final Intent detectedIntent;
    private final Instant timestamp;

    /**
     * Creates a new ConversationTurn with the current timestamp.
     *
     * @param userMessage    The message from the user
     * @param botResponse    The response from the bot
     * @param detectedIntent The intent detected for this turn (can be null)
     */
    public ConversationTurn(String userMessage, String botResponse, Intent detectedIntent) {
        this(userMessage, botResponse, detectedIntent, Instant.now());
    }

    /**
     * Creates a new ConversationTurn with a specific timestamp.
     *
     * @param userMessage    The message from the user
     * @param botResponse    The response from the bot
     * @param detectedIntent The intent detected for this turn (can be null)
     * @param timestamp      The timestamp of the turn
     */
    public ConversationTurn(String userMessage, String botResponse, Intent detectedIntent, Instant timestamp) {
        this.userMessage = userMessage;
        this.botResponse = botResponse;
        this.detectedIntent = detectedIntent;
        this.timestamp = timestamp;
    }

    public String getUserMessage() {
        return userMessage;
    }

    public String getBotResponse() {
        return botResponse;
    }

    /**
     * Gets the detected intent.
     *
     * @return The matched Intent object, or null if the input was unrecognized
     */
    public Intent getDetectedIntent() {
        return detectedIntent;
    }

    public Instant getTimestamp() {
        return timestamp;
    }

    @Override
    public String toString() {
        return "ConversationTurn{" +
                "userMessage='" + userMessage + '\'' +
                ", botResponse='" + botResponse + '\'' +
                ", detectedIntent=" + (detectedIntent != null ? detectedIntent.getTag() : "null") +
                ", timestamp=" + timestamp +
                '}';
    }
}
